### ISSUE TITLE
Subscribe for keyboard closing event

### ISSUE THREAD

**Issue by fcmaia** [by-pinja/ng-virtual-keyboard#12]
Is it possible to subscribe or define a callback for the moment when the user ends typing?

**Comment by Bartoszkolodziejczak** [comment]
Something moved on the subject?

**Comment by Hekku2** [comment]
Probably coming next. #59

**Comment by Hekku2** [comment]
Fxed in [v0.11.0](https://www.npmjs.com/package/@protacon/ng-virtual-keyboard/v/0.11.0)
