### ISSUE TITLE
Backspace not updating model

### ISSUE THREAD

**Issue by srmiranda** [by-pinja/ng-virtual-keyboard#16]
The backspace key doesn't fire a key event and isn't updating the model unless you press a new key. If you have "aaa" and backspace, it won't update unless you hit "b", making it "aab" as an example. Otherwise, backspacing makes no change to the model until you change what it originally was by adding new characters or numbers.

**Comment by tarlepp** [comment]
Could you make an PR to solve this issue?

**Comment by newtask** [comment]
just add "this.dispatchEvents(event);" after line 278 in src/virtual-keyboard.component.ts

This solves this issue.

**Comment by Hekku2** [comment]
This is now fixed in release 0.9.1
