### ISSUE TITLE
Incompatible with angular 7. Production build fails.

### ISSUE THREAD

**Issue by adriancoca** [by-pinja/ng-virtual-keyboard#28]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 0.8.0
| Angular version | 7.2.2

Build fails (ng build --prod)  when using this library with Angular 7.

ERROR in node_modules/@protacon/ng-virtual-keyboard/node_modules/@angular/flex-layout/core/typings/match-media/mock/mock-match-media.d.ts(25,15): error TS2416: Property '_registry' in type 'MockMatchMedia' is not assignable to the same property in base type 'MatchMedia'.
........
I think package.json should be updated to be compatible with angular 7.

**Comment by harryhahn** [comment]
I have the same issus. 
does anyone have a solution please.

**Comment by tarlepp** [comment]
We're always open for PR's to fix this.

**Comment by Hekku2** [comment]
Now it should be fixed in release https://github.com/by-pinja/ng-virtual-keyboard/releases/tag/v0.9.0
